const API=window.SOCIETY_API_URL||"http://localhost:8000";const $=id=>document.getElementById(id);const state={user:null,tasks:[]};
async function api(path,o={}){const r=await fetch(API+path,{credentials:"include",headers:{"Content-Type":"application/json",...(o.headers||{})},...o});if(!r.ok){let m="Request failed";try{const x=await r.json();m=x.detail||m}catch{}throw Error(m)}return r.status===204?null:r.json()}
function showApp(){$("login-view").hidden=true;$("app-view").hidden=false;$("user-name").textContent=state.user.display_name;$("user-role").textContent=state.user.role;$("create-panel").hidden=state.user.role==="MANAGER"}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function render(){const ss=["ASSIGNED","IN_PROGRESS","COMPLETED","REVIEWED"];const cs=ss.map(s=>state.tasks.filter(t=>t.status===s).length);$("stats").innerHTML=[["Assigned",cs[0]],["In progress",cs[1]],["Completed",cs[2]],["Reviewed",cs[3]]].map(x=>"<div class=\"stat\"><b>"+x[1]+"</b><span>"+x[0]+"</span></div>").join("");$("tasks").innerHTML=state.tasks.length?state.tasks.map(taskHtml).join(""):"<div class=\"muted\">No tasks in the queue.</div>"}
function taskHtml(t){const manager=state.user.role==="MANAGER";let a="";if(manager&&t.status==="ASSIGNED")a="<button data-action=\"start\" data-id=\""+t.id+"\">Start</button>";if(manager&&t.status==="IN_PROGRESS")a="<button data-action=\"complete\" data-id=\""+t.id+"\">Complete</button>";if(!manager&&t.status==="COMPLETED")a="<button data-action=\"approve\" data-id=\""+t.id+"\">Approve</button><button class=\"ghost\" data-action=\"return\" data-id=\""+t.id+"\">Return</button>";return "<article class=\"task\"><div class=\"task-head\"><div><div class=\"task-title\">"+esc(t.title)+"</div><div class=\"muted\">"+esc(t.description||"")+"</div></div><span class=\"tag "+t.status.toLowerCase()+"\">"+t.status.replaceAll("_"," ")+"</span></div><div class=\"task-meta\"><span class=\"tag\">"+t.priority+"</span>"+(t.due_date?"<span class=\"tag\">Due "+new Date(t.due_date).toLocaleDateString()+"</span>":"")+"</div>"+(t.completion_remarks?"<p><b>Completion:</b> "+esc(t.completion_remarks)+"</p>":"")+(t.review_remarks?"<p><b>Review:</b> "+esc(t.review_remarks)+"</p>":"")+(a?"<div class=\"actions\">"+a+"</div>":"")+"</article>"}
async function load(){state.tasks=await api("/tasks");render()}
$("login-form").addEventListener("submit",async e=>{e.preventDefault();$("login-error").textContent="";try{state.user=await api("/auth/login",{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value})});showApp();await load()}catch(x){$("login-error").textContent=x.message}});
$("logout").addEventListener("click",async()=>{await api("/auth/logout",{method:"POST"});location.reload()});$("refresh").addEventListener("click",load);
$("task-form").addEventListener("submit",async e=>{e.preventDefault();const d=$("due-date").value;await api("/tasks",{method:"POST",body:JSON.stringify({title:$("title").value,description:$("description").value,priority:$("priority").value,due_date:d?new Date(d+"T23:59:59").toISOString():null})});e.target.reset();await load()});
$("tasks").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const id=b.dataset.id;try{if(b.dataset.action==="start")await api("/tasks/"+id+"/start",{method:"POST"});if(b.dataset.action==="complete"){const r=prompt("Completion remarks / evidence:");if(!r)return;await api("/tasks/"+id+"/complete",{method:"POST",body:JSON.stringify({completion_remarks:r})})}if(b.dataset.action==="approve"||b.dataset.action==="return"){const r=prompt("Review remarks:")||"";await api("/tasks/"+id+"/review",{method:"POST",body:JSON.stringify({approved:b.dataset.action==="approve",review_remarks:r})})}await load()}catch(x){alert(x.message)}});
(async()=>{try{state.user=await api("/auth/me");showApp();await load()}catch{}})();